"""relationships bw group and post

Revision ID: 53f83ee3d6c6
Revises: c99f8a1af16a
Create Date: 2018-06-08 15:48:45.828329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f83ee3d6c6'
down_revision = 'c99f8a1af16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'group_id')
    # ### end Alembic commands ###
