"""comment group relationship

Revision ID: 7fc5b95536f9
Revises: a3cd48f2bbe9
Create Date: 2018-06-11 12:09:02.921332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc5b95536f9'
down_revision = 'a3cd48f2bbe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'group', ['post_id'], ['id'])
    op.drop_column('comment', 'group_id')
    # ### end Alembic commands ###
